# CHANGE this passphrase to something secret. If you lose it, you won't be able to decrypt existing teams.yml data.
encryption-passphrase: "change_this_passphrase_immediately"


# Save interval (seconds)
autosave-interval: 60


# Team name restrictions
team-name-min-length: 2
team-name-max-length: 24
team-name-allowed-regex: "^[A-Za-z0-9_-]+$"