name: TeamsPlugin
main: com.example.teamplugin.TeamsPlugin
version: 1.0
api-version: 1.21
author: yourname
commands:
  team:
    description: Team management command
    usage: /team <subcommand>
    permission: teams.use
permissions:
  teams.use:
    description: Allows use of /team commands
    default: true
